config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    authenticated :user do
      root :to => "users#show", as: :authenticated_root
    end
    unauthenticated :user do
      root :to => "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new,:create,:show] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
  end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post
  after_save :update_comments_counter

  validates :text, presence: true, length: { minimum: 1 }
  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post
  after_save :update_likes_counter
  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments
  has_many :likes
  after_save :update_post_counter

  validates :title, presence: true, length: { minimum: 4, maximum: 250 }
  validates :comments_counter, presence: true,
                               numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true,
                            numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def update_post_counter
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.includes(:author).order('created_at desc').limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true, length: { in: 3..32 }
  validates :photo, presence: true, length: { minimum: 20, maximum: 2000 }
  validates :posts_counter, presence: true,
                            numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def all_users
    User.all.order('id asc')
  end

  def current_post
    User.find(params[:user_id]).posts.find(params[:id] || params[:post_id])
  end

  def all_users_post_controller
    User.find(params[:user_id])
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo bio])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name photo bio])
    devise_parameter_sanitizer.permit(:sign_in) do |user_params|
      user_params.permit(:username, :email)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    respond_to do |format|
      format.html { render :new, locals: { comment: Comment.new } }
    end
  end

  def create
    user = current_user
    post = current_post
    comment = Comment.new(comment_params)
    comment.author = user
    comment.post = post
    if comment.save
      flash[:success] = 'Comment saved successfully'
      redirect_to user_post_url(id: post.id)
    else
      flash[:error] = 'Error: Comment could not be saved'
      redirect_to new_user_post_comment_url
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    user = current_user
    post = current_post
    post.likes.where("author_id = #{user.id}").length.positive? && (
      flash[:error] = 'Error: you already liked it.'
      where_to_redirect(post)
      return
    )
    like = Like.new(author: user, post:)
    unless like.save
      flash[:error] = 'Error: Like could not be saved'
      where_to_redirect(post)
      return
    end
    where_to_redirect(post)
  end

  private

  def where_to_redirect(post)
    if params[:distination] == 'index'
      redirect_back_or_to user_posts_url
    else
      redirect_back_or_to user_post_url(id: post.id)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = all_users_post_controller
    @posts = @user.posts.includes(:comments).order('id asc')
  end

  def show
    @post = current_post
  end

  def new
    respond_to do |format|
      format.html { render :new, locals: { post: Post.new } }
    end
  end

  def create
    user = current_user
    post = Post.new(post_params)
    post.author = user
    if post.save
      flash[:success] = 'Post saved successfully'
      redirect_to user_posts_url
    else
      flash[:error] = 'Error: Post could not be saved'
      redirect_to new_user_post_url
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = all_users
  end

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/llkes_helper.rb
module LikesHelper
end

app/helpers/posts_helpers.rb
module PostsHelper
end

app/helpers/users_helpers.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%=form_with model:[:user,:post, comment], method: :post, id: 'form' do |form| %>
  <%=label(:comment,:Comment)%> 
  <%=form.text_area :text%>
  <%=form.submit "Add comment" %>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
      <p id="red"><%=flash[:error]%></p> 
      <p id="blue"><%=flash[:success]%></p> 
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<%=
form_with model:like, url:user_post_likes_url(post_id:post_id,distination: distination), remote:true, 
method: :post, id: 'form' do |form| %>
  <%=form.submit "Add like", class:"add-like" %>
<% end %> 

app/views/posts/_comments.html.erb
<p>
<span class="comment"><%=comment.author.name%>:</span> 
<span class="comment"><%=comment.text%></span>
</p> 

app/views/posts/_post.html.erb
<%=link_to user_post_path(id:post.id) do%>
<section class="user-info">
<h4><%=post.title%></h4>
 <p>
   <%= 
     post.text.length > 100 && post.text + "..."
     post.text unless post.text.length > 100 
   %>   
</p>
 <small>
    Comments: <%=post.comments_counter%>, Likes: <%=post.likes_counter%>       
</small> 
 <%=render partial:'likes/like', locals:{like:@like,post_id:post.id,distination:params[:action]}%>
</section>
<%end%>

app/views/posts/_post_information.html.erb
<section class="user-info">
<h4><%=post.title%> by <%=post.author.name%></h4>
 <p><%=post.text%></p>
 <small>
    Comments: <%=post.comments_counter%>, Likes: <%=post.likes_counter%>       
</small> 
<%=link_to new_user_post_comment_path(post_id:post.id) do%>
   <button class="create-comment">Create comment</button>
  <%end%> 
<%=render partial:'likes/like', locals:{like:@like,post_id:post.id,distination:params[:action]}%> 
</section>
<%if post.comments.length > 0 %>
<section class="comment-section">
   <%= render partial:'comments', as: 'comment', collection:comments%>
</section> 
<%end%>  

app/views/posts/_posts.html.erb
<section class="user-info">
<h4><%=post.title%></h4>
 <p><%=post.text%></p>
 <small>
    Comments: <%=post.comments_counter%>, Likes: <%=post.likes_counter%>       
</small> 
</section>
<section class="comment-section">
   <%= render partial:'comments', as: 'comment', collection:post.comments%>
</section>   

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>user's posts</title>
</head>
<body>
  <main id ="container"> 
  <%= render partial:'users/user', locals:{user: @user} %>
  <%=link_to new_user_post_path do%>
   <button class="create-post">Create post</button>
  <%end%>
   <% @posts.each do |post| %>
  <%= render post%>
   <%if post.comments.length > 0 %>
   <section class="comment-section">
    <%= render partial:'comments', as: 'comment', collection:post.recent_comments%>
   </section>
   <%end%>
   <%end%>
  <button id="show-posts">pagination</button>
</main>     
</body>
</html>

app/views/posts/new.html.erb
<%=form_with model: [:user, post], method: :post, id: 'form' do |form| %>
  <%=label(:post,:Title)%> 
  <%=form.text_field :title%>
  <%=label(:post,:Topic)%> 
  <%=form.text_area :text%>
  <%=form.submit "Save" %>
<% end %>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>specific post</title>
</head>
<body>
  <main id ="container">
   <%= render partial: "post_information", locals: {post:@post,comments:@post.comments.includes(:author)}%>
  </main> 
</body>
</html>

app/views/users/_bio.html.erb
<section id="bio">
	<h3>Bio</h3>
	<p><%=bio%></p>
</section>	

app/views/users/_user.html.erb
<section class="user">
  <img class="image" src="<%=user.photo%>" alt="user-image" />
  <%= link_to user_path(user) do%>
  <div class="card">
     <h2><%= user.name%> </h2>
     <p> Number of posts: <%= user.posts_counter%></p>
  </div class="card">
  <%end%>
</section> 

app/views/users/_user_information.html.erb
<%= link_to user_post_path(@user,id:post.id) do%>
<section class="user-info">
<h4><%=post.title%></h4>
 <p><%=post.text%></p>
 <small>
    Comments: <%=post.comments_counter%>, Likes: <%=post.likes_counter%>       
</small>
</section>
<%end%>	

app/views/users/index.html.erb
<%= stylesheet_link_tag "users" %>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>users</title>
</head>
<body>
    <main id ="container">  
    <%= render @users %>
    </main>
</body>
</html>

app/views/users/show.html.erb
<%= stylesheet_link_tag "user_info" %>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>specific user</title>
</head>
<body>
<main id ="container"> 
  <%= render @user%>
  <%= render partial: "bio" , locals:{bio:@user.bio}%>
  <%= render partial: "user_information", as: "post" , collection: @user.recent_posts%>
  <button id="show-posts"><%= link_to "See all posts", user_posts_path(@user) %></button>
  </main>
</body>
</html>